All your codebase are belong to us.

diff --git a/.github/workflows/create_argocd_app.yml b/.github/workflows/create_argocd_app.yml
--- a/.github/workflows/create_argocd_app.yml
+++ b/.github/workflows/create_argocd_app.yml
@@ -103,23 +103,51 @@ jobs:
           git status
           git commit -m "Create ${NAMESPACE}/${APP_NAME}" -m 'Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
 
-#      - name: Push
-#        shell: bash
-#        run: |
-#          set -xeuo pipefail
-#
-#          attempt=0
-#          max_attempts=5
-#          while ! git push; do
-#            attempt=$((attempt+1))
-#            if [ $attempt -ge $max_attempts ]; then
-#              echo "Max attempts reached. Exiting."
-#              exit 1
-#            fi
-#            sleep_time=$((RANDOM % 10 + 1))
-#            echo "Push failed. Attempting retry (${attempt}/${max_attempts}) in ${sleep_time} seconds..."
-#            sleep $sleep_time
-#            git pull --rebase
-#          done
-#
-#          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
+      - name: Push
+        id: push
+        shell: bash
+        run: |
+          set -xeuo pipefail
+
+          attempt=0
+          max_attempts=5
+          while ! git push; do
+            attempt=$((attempt+1))
+            if [ $attempt -ge $max_attempts ]; then
+              echo "Max attempts reached. Exiting."
+              exit 1
+            fi
+            sleep_time=$((RANDOM % 10 + 1))
+            echo "Push failed. Attempting retry (${attempt}/${max_attempts}) in ${sleep_time} seconds..."
+            sleep $sleep_time
+            git pull --rebase
+          done
+
+          echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
+
+      - name: Get GitHub user details
+        uses: actions/github-script@v6
+        env:
+          PR_NUMBER: ${{ github.event.number }}
+          COMMIT_SHA: ${{ steps.push.output.commit_sha }}
+        with:
+          github-token: ${{ secrets.GIT_PAT }}
+          script: |
+            const { repo, owner } = context.repo;
+            const [infraOwner, infraRepo] = process.env.INFRA_REPO.split('/');
+            const prNumber = process.env.PR_NUMBER;
+            const commit_sha = process.env.COMMIT_SHA;
+            
+            if (prNumber) {
+              const { data: commit } = github.rest.git.getCommit({
+                owner: infraOwner,
+                repo: infraRepo,
+                commit_sha: commit_sha,
+              });
+              await github.rest.issues.createComment({
+                owner: owner,
+                repo: repo,
+                issue_number: prNumber,
+                body: `Commit ${commit.html_url} is created.`,
+              });
+            }
